### ISSUE TITLE
fastAAI: sqlite3.OperationalError

### ISSUE THREAD

**Issue by KGerhardt** [KGerhardt/FastAAI#1]
Since Issues are not available for [FastAAI](https://github.com/KGerhardt/FastAAI), I'm posting my issue here. I'll switch it over to the appropriate repo when it is possible.

Setup
Conda env setup as in the instructions.

Using prodigal-generated amino acid sequences.

fastAAI run:

fastaai aai_index   --threads 12     -p /path/to/prodigal/protein_files/ -o $OUTDIR
Error
Starting from proteins

FastAAI is formatting your files to be saved to your database.

Formatting data to add to database at 10/04/2022 07:48:04

Adding data to final database.

Database build complete!

Performing an all vs. all query on FastAAI/database/FastAAI_database.sqlite.db

Loading query data at 10/04/2022 07:48:05 ...

Loading target data at 10/04/2022 07:48:06 ...

FastAAI will search 9 query genomes against 9 target genomes.

Beginning AAI calculation at 10/04/2022 07:48:06multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/site-packages/fastaai/FastAAI.py", line 2270, in do_sql_query_no_SD
    database.cursor.execute(temp_tab)
sqlite3.OperationalError: near "-": syntax error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/bin/fastaai", line 8, in <module>
    sys.exit(main())
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/site-packages/fastaai/FastAAI.py", line 3715, in main
    aai_index(genomes, proteins, hmms, db_name, output, threads, gf, pf, hf, verbose, do_stdev, mem, efficient)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/site-packages/fastaai/FastAAI.py", line 3319, in aai_index
    db_query(accessible_name, accessible_name, verbose, output, threads, do_stdev, memory_use, unlimited_resources)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/site-packages/fastaai/FastAAI.py", line 2442, in db_query
    do_query_vs_target_sql(query, target, threads, output, verbose, do_stdev)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/site-packages/fastaai/FastAAI.py", line 2126, in do_query_vs_target_sql
    for file in pool.imap(do_sql_query_no_SD, query_args):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/e597b1bc4c3f6c65a46887160aeefc74/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
sqlite3.OperationalError: near "-": syntax error
The error is due to input file names that include a -. For example: Ruminococcus_bromii_strain_AM46-2B.faa

###########################################################################################

FastAAI errors when using a directory path for -o (e.g., /path/to/output/directory/), instead of just an output directory name (e.g., fastaai_output):

$ fastaai aai_index --threads 8 -g genomes -o tmp/test_out
Starting from genomes

FastAAI is formatting your files to be saved to your database.

Error: can't open output file test_out/predicted_proteins/TAS386.temp.

Error: can't open output file test_out/predicted_proteins/TAS122.temp.

Error: can't open output file test_out/predicted_proteins/TAS067.temp.

Error: can't open output file test_out/predicted_proteins/TAS386.temp.

Error: can't open output file test_out/predicted_proteins/TAS122.temp.

Error: can't open output file test_out/predicted_proteins/TAS067.temp.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 961, in do_advance
    input_file_object.preprocess()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 881, in preprocess
    self.genome_to_protein()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 673, in genome_to_protein
    temp_output.unlink()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/pathlib.py", line 1309, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: 'test_out/predicted_proteins/TAS067.temp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/bin/fastaai", line 8, in <module>
    sys.exit(main())
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 3715, in main
    aai_index(genomes, proteins, hmms, db_name, output, threads, gf, pf, hf, verbose, do_stdev, mem, efficient)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 3316, in aai_index
    success = build_db(genomes, proteins, hmms, db_name, output, threads, gf, pf, hf, verbose)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 1622, in build_db
    success = add_inputs(output, final_database, existing_genome_IDs, threads, verbose, prep_args)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 1305, in add_inputs
    inputs = advance_inputs(genomes = genomes, proteins = proteins, hmms = hmms, genomes_file = gf, proteins_file = pf, hmms_file = hf, output = output_path, threads = threads, verbose = verbose, db_name = db_name)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/site-packages/fastaai/FastAAI.py", line 1102, in advance_inputs
    for res in pool.imap(do_advance, inputs):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/tmp/fastAAI/fastaai_env/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'test_out/predicted_proteins/TAS067.temp'
Error 3
FastAAI also cannot create a full directory path:

FastAAI tried to make output directory: 'tmp/test_out' but failed.
Using os.makedirs would fix this.

**Comment by KGerhardt** [comment]
**First issue:**

The identifier taken from a file is done as such:

basename = os.path.splitext(os.path.basename(input_path))[0]

This does leave it open to including non-allowable characters that will break things later. I'll add a step sanitizing out impermissible SQLite characters.

**Second issue:**

Thank you for identifying this. Yes, it seems like an inappropriate path manipulation resulted in the removal of parent directories, leaving only the final one. I'll fix this.

**Third issue:**

I'm not sure I regard this one as an error. I would prefer to avoid making a call that recursively creates directories on a system. FastAAI already creates a top-level, organizational directory for its kinds of outputs. Is there a strong use case you have in mind?

**Comment by nick-youngblut** [comment]
>I'm not sure I regard this one as an error. I would prefer to avoid making a call that recursively creates directories on a system

Yeah, that can be a hard call for developers creating software for biologists that may be less familiar with the command line. I tend to go with "we are all consenting adults here", and like the convinces of not having to pre-generate the output file path or use `--force-overwrite` if I want to re-run a command. But then again, such safeguards can be helpful for other users.

**Comment by KGerhardt** [comment]
I fixed the issue with directory paths and I added a sanitization step that simply replaces characters in file names outside the permissible SQL set with underscores. It's not the most elegant solution, but it will work for the moment.

As to the multiple levels of directory creation, rerunning a command with FastAAI that reuses an output path should not cause issues. Proteins, HMMs, and results all overwrite by default when file name matches and the same output directory is reused. Perhaps I should even change this so that there is a check for a --force-overwrite in that case. 

For building databases, this is intentional: the build command allows you to build a new database or add new genomes which require preprocessing to an existing one. If you build a database from 10 genomes and reuse the same build command, except specifying a different set of genomes, those new genomes will be *added* to the existing database, not overwrite anything.

**Comment by nick-youngblut** [comment]
Thanks @KGerhardt for updating the code so quickly! 

Do you accept PRs? I did fork the repo and was going to try and make the changes myself, but then I saw that the repo doesn't include a `setup.py`, so I wasn't going to mess with a non-standard python package install.

**Comment by KGerhardt** [comment]
Well there is a pip version up, as well - https://pypi.org/project/FastAAI/ I just updated it with these changes.

I'll also add the whole pypi installation directory to this GH. Everything it needs should be there.

At the moment, I can't change anything substantial, so I can't accept pulls at the moment. The code is part of a manuscript under review, and while a fix in something like a path error doesn't change anything relevant in the operation of the tool, more significant changes might.
